### ISSUE TITLE
Debug ble problems with Circuitpython > 9.1.0

### ISSUE THREAD

**Issue by silvioheinze** [luftdaten-at/firmware#25]

**Comment by n11ik** [comment]
Issue was fixed in the circuitpython version [9.2.0-alpha](https://adafruit-circuit-python.s3.amazonaws.com/bin/espressif_esp32s3_devkitc_1_n8r8/en_US/adafruit-circuitpython-espressif_esp32s3_devkitc_1_n8r8-en_US-9.2.0-alpha.2351.bin) and will be fixed in the 9.2 release.
See: https://github.com/adafruit/circuitpython/issues/9669
